// Android project setup performed by `dart run embedded_devtools:init`.
//
// The in-app WebView loads the DevTools server over plain http on loopback,
// which Android denies by default (API 28+). We grant a *loopback-scoped*
// exception, and only for debug/profile builds — release never runs the server
// (no VM service), so the exception must not exist in production.
import 'dart:io';

const _configPath = 'android/app/src/main/res/xml/network_security_config.xml';
const _configRef = '@xml/network_security_config';

const _configXml = '''
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by embedded_devtools.

     Lets the in-app DevTools WebView reach the embedded server over plain
     http on loopback. Scoped to localhost only — every other domain keeps the
     platform default (cleartext denied). Referenced only from the debug and
     profile manifests, so it has no effect on release builds. -->
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">127.0.0.1</domain>
        <domain includeSubdomains="true">localhost</domain>
    </domain-config>
</network-security-config>
''';

const _manifestTemplate = '''
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <!-- The INTERNET permission is required for development: the Flutter tool
         needs it to communicate with the running application. -->
    <uses-permission android:name="android.permission.INTERNET"/>

    <!-- embedded_devtools: allow the in-app DevTools WebView to reach the
         loopback server. Not present in release. -->
    <application android:networkSecurityConfig="$_configRef" />
</manifest>
''';

/// Wires up the Android project. Returns true if the project looks Android-y
/// and setup succeeded (or was already done).
bool setupAndroid() {
  if (!Directory('android/app').existsSync()) {
    stdout.writeln('• No android/app directory — skipping Android setup.');
    return true;
  }

  final config = File(_configPath);
  if (config.existsSync()) {
    stdout.writeln('• $_configPath already exists — left as is');
  } else {
    config
      ..createSync(recursive: true)
      ..writeAsStringSync(_configXml.trimLeft());
    stdout.writeln('✓ wrote $_configPath');
  }

  // If the main manifest already declares its own config, ours would collide
  // in the manifest merger. Don't silently fight it.
  final main = File('android/app/src/main/AndroidManifest.xml');
  if (main.existsSync() &&
      main.readAsStringSync().contains('android:networkSecurityConfig')) {
    stdout.writeln(
        '! android/app/src/main/AndroidManifest.xml already sets\n'
        '  android:networkSecurityConfig. Leaving the build-type manifests\n'
        '  alone to avoid a merge conflict — make sure your config permits\n'
        '  cleartext to 127.0.0.1, or the DevTools tab shows\n'
        '  ERR_CLEARTEXT_NOT_PERMITTED.');
    return true;
  }

  for (final buildType in ['debug', 'profile']) {
    _patchBuildTypeManifest(buildType);
  }
  return true;
}

/// Adds the network-security-config reference to a build-type manifest,
/// creating it if absent.
void _patchBuildTypeManifest(String buildType) {
  final path = 'android/app/src/$buildType/AndroidManifest.xml';
  final file = File(path);

  if (!file.existsSync()) {
    file
      ..createSync(recursive: true)
      ..writeAsStringSync(_manifestTemplate.trimLeft());
    stdout.writeln('✓ created $path');
    return;
  }

  final content = file.readAsStringSync();
  if (content.contains('android:networkSecurityConfig')) {
    stdout.writeln('• $path already configured');
    return;
  }

  // Insert an <application> element before </manifest>.
  const application =
      '    <!-- embedded_devtools: allow the in-app DevTools WebView to reach\n'
      '         the loopback server. Not present in release. -->\n'
      '    <application android:networkSecurityConfig="$_configRef" />\n';
  final close = content.lastIndexOf('</manifest>');
  if (close == -1) {
    stderr.writeln('! $path has no </manifest> — add this inside <manifest>:\n'
        '$application');
    return;
  }
  final patched =
      content.replaceRange(close, close, '\n$application');
  file.writeAsStringSync(patched);
  stdout.writeln('✓ patched $path');
}
